# An example Trunk.toml with all possible fields along with their defaults.

# A sem-ver version requirement of trunk required for this project
trunk-version = "*"

[build]
# The index HTML file to drive the bundling process.
target = "src/index.html"
# The output dir for all final assets.
dist = "dist"
# The public URL from which assets are to be served.
public_url = "/dist/"
